export enum TOOLTIP_MESSAGE {
  INVALID_WORD = 'INVALID_WORD',
  WORD_ALREADY_USED = 'WORD_ALREADY_USED',
  CORRECT_LETTER_POSITION = 'CORRECT_LETTER_POSITION',
  LETTER_NOT_IN_WORD = 'LETTER_NOT_IN_WORD',
  INCORRECT_LETTER_POSITION = 'INCORRECT_LETTER_POSITION'
}
